export const browserCoreExamples = [
  "theclaw browser status",
  "theclaw browser start",
  "theclaw browser start --headless",
  "theclaw browser stop",
  "theclaw browser tabs",
  "theclaw browser open https://example.com",
  "theclaw browser focus abcd1234",
  "theclaw browser close abcd1234",
  "theclaw browser screenshot",
  "theclaw browser screenshot --full-page",
  "theclaw browser screenshot --ref 12",
  "theclaw browser snapshot",
  "theclaw browser snapshot --format aria --limit 200",
  "theclaw browser snapshot --efficient",
  "theclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "theclaw browser navigate https://example.com",
  "theclaw browser resize 1280 720",
  "theclaw browser click 12 --double",
  "theclaw browser click-coords 120 340",
  'theclaw browser type 23 "hello" --submit',
  "theclaw browser press Enter",
  "theclaw browser hover 44",
  "theclaw browser drag 10 11",
  "theclaw browser select 9 OptionA OptionB",
  "theclaw browser upload /tmp/theclaw/uploads/file.pdf",
  'theclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "theclaw browser dialog --accept",
  'theclaw browser wait --text "Done"',
  "theclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "theclaw browser console --level error",
  "theclaw browser pdf",
];
